version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data/

  web:
    build: .
    command: sh -c "python manage.py migrate && 
          gunicorn --bind 0.0.0.0:8000 --pythonpath sitFic sitFic.wsgi:application "      
    volumes:
      - ./sitFic:/code
      - ./sitFic/adminlte/static:/static
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db      
  
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx:/etc/nginx/conf.g
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  db_data: